version: 2
jobs:
  build:
    docker:
       - image: ubuntu
         auth:
                  username: arpan2009
                  password: arpan@2009
       - image: mariadb
         auth:
                  username: arpan2009
                  password: arpan@2009
         environment: 
          MYSQL_ROOT_PASSWORD=2009
    steps:
      - checkout 
      #- run: apt update
      #- run: apt install -y node 
      