version: 2
jobs:
  build:
    docker:
       - image: cimg/node:18.9.0
         auth:
                  username: arpan2009
                  password: arpan@2009
       - image: cimg/mysql:8.0
         auth:
                  username: arpan2009
                  password: arpan@2009
         environment: 
          MYSQL_ROOT_PASSWORD=2009
    steps:
      - checkout 
      - run: npm install -g localtunnel
      - run: lt --port 3306
      